In [7]:
import numpy as np;
a=np.array([1,2,3,4,5,6])
x=np.where(a==4)
print(x)

(array([3]),)


In [10]:
import numpy as np;
a=np.array([1,6,2,7,6,4])
x=np.where(a/2)
print(x)

(array([0, 1, 2, 3, 4, 5]),)


In [17]:
import numpy as np;
arr=np.array([0,1,2,3,7,8,9])
x=np.searchsorted(arr,8,side='left')
print(x)

5


In [18]:
import numpy as np;
a=np.sort([3,5,4,3,5])

x=np.sort(a)
print(x)

[3 3 4 5 5]


In [20]:
import numpy as np;
a=np.array([[1,3,5,4],[4,3,2,6]])
x=np.sort(a)
print(x)

[[1 3 4 5]
 [2 3 4 6]]


In [25]:
import numpy as np;
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]


In [ ]:
import numpy as np;
