In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
import numpy as np
flat=a.flatten()
a=np.array([[1,2,3],[5,2,4],[2,4,6]])
b=np.zeros((5,3))
c=np.random.random((5,3))
d=a.reshape((3,3))
print("\n array with all zeroes:\n",b)
print("\n random values:\n",c)
print("\n reshape values:\n",d)
print("flatten array:\n",flat)


 array with all zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 random values:
 [[0.16916671 0.53501801 0.44699013]
 [0.02653179 0.01311642 0.99089316]
 [0.02083132 0.99402061 0.04353939]
 [0.31107124 0.0997226  0.2492166 ]
 [0.92025458 0.27051419 0.19493238]]

 reshape values:
 [[1 2 3]
 [5 2 4]
 [2 4 6]]
flatten array:
 [1 2 3 5 2 4 2 4 6]


In [42]:
import numpy as np
a=np.array([[1,2,3],[5,2,4],[2,4,6]])
flat=a.flatten()
print("flatten array:\n",flat)
print("Dimension:\n",a.ndim)


flatten array:
 [1 2 3 5 2 4 2 4 6]
Dimension:
 2


In [46]:
import numpy as np
arr=np.array([[1,2,3],[5,2,4],[2,4,6]])
print("\n shape of array:",arr.shape)


 shape of array: (3, 3)


In [34]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
newtype=a.astype('f')
print("\n count array element \n",newtype)
print("\n converted array:",newtype.dtype)


 count array element 
 [[1. 2. 3.]
 [3. 4. 5.]]

 converted array: float32


In [35]:
print("\n size of array:",a.size)


 size of array: 6
