In [1]:
import numpy as np;
a=np.array([10,20,30,40])
print("onr dimensional array",a)

onr dimensional array [10 20 30 40]


In [3]:
import numpy as np;
b=np.array([[10,20,30,40],[10,20,30,40]])
print("two dimensional array",b)

two dimensional array [[10 20 30 40]
 [10 20 30 40]]


In [4]:
import numpy as np;
c=np.array([[10,20,30,40],[10,20,30,40]])
print("three dimensional array",c)

three dimensional array [[10 20 30 40]
 [10 20 30 40]]


In [6]:
import numpy as np;
d=np.zeros((3,5))
print("\n zero array \n",d)


 zero array 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
import numpy as np;
f=np.random.random((1,3))
print("\n random value \n",f)


 random value 
 [[0.2140503  0.08175881 0.58649622]]


In [11]:
import numpy as np;
e=np.arange(0,18,11)
print("\n random value\n",e)


 random value
 [ 0 11]


In [12]:
import numpy as np;
f=np.array([[18,11,21,29],[11,18,21,29],[21,29,11,18]])
newarray=f.reshape((4,3))
print("\n original array\n",f)
print("\n reshaped array \n",newarray)


 original array
 [[18 11 21 29]
 [11 18 21 29]
 [21 29 11 18]]

 reshaped array 
 [[18 11 21]
 [29 11 18]
 [21 29 21]
 [29 11 18]]


In [14]:
import numpy as np;
b=np.array([[18,11,21],[11,18,21]])
g=b.flatten()
print("original array:",b)
print("flattened array:",g)


original array: [[18 11 21]
 [11 18 21]]
flattened array: [18 11 21 11 18 21]


In [15]:
import numpy as np;
a=np.array([[8,1,2],[1,8,2]])
dimension=a.ndim
print("\n dimension of the array:",dimension)


 dimension of the array: 2


In [17]:
import numpy as np;
a=np.array([[[8,1,2],[1,8,2],[2,1,8]]])
dimension=a.ndim
print("\n dimension of the array:",dimension)


 dimension of the array: 3


In [18]:
import numpy as np;
f=np.array([[1,8,2],[8,1,2]])
shape=f.shape
print("shape of the array:",shape)

shape of the array: (2, 3)


In [19]:
import numpy as np;
g=np.array([[11,18,21],[18,11,21]])
print("\n array element:",g.dtype)


 array element: int64


In [20]:
import numpy as np;
s=np.array([7,10,11])
print("\n lenght of array:",len(s))


 lenght of array: 3
