In [5]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b))
sclr=3
print("result:",a*sclr)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]
1150
result: [ 60 120 150 210  30]


In [6]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [18]:
import numpy as np
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,7,2]
arr2=[6,5,3]
vect=np.vectorize(my_func)
print("array1:",arr1)
print("array2:",arr2)
print("result:",vect(arr1,arr2))

array1: [10, 7, 2]
array2: [6, 5, 3]
result: [4 2 5]
