In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [9]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [11]:
reversed=arr[::-1]
print(reversed)

[9 8 7 6 5 4 3 2 1]


In [15]:
import numpy as np
arr=np.array(([1,2,3,4],[2,4,6,8],[3,4,5,7]))
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [4 6]]


In [18]:
col=arr[:,0]
print(col)

[1 2 3]


In [20]:
row=arr[1,:]
print(row)

[2 4 6 8]


In [24]:
print(arr[0,0])

1


In [25]:
print(arr[1,2])

6


In [28]:
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [29]:
print(arr[1:4])

[20 30 40]


In [31]:
print(arr[arr>25])

[30 40 50]


In [35]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)
#it adds element top of each other

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)
#it adds element top of each other

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [41]:
#splitting in numpy
import numpy as np
arr1=np.array([1,2,3,4,5,6])
result=np.split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
result=np.array_split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
